name: test

on:
  workflow_dispatch:

jobs:
  try_commit_workflow_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.WORKFLOW_CLIENT_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
      - name: Configure git credentials
        run: |
          git config user.name "asdf-test-app"
          git config user.email "support@asdf-format.org"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
      - id: branch
        run: echo name=commit_workflow_changes >> $GITHUB_OUTPUT
      - run: git checkout -b ${{ steps.branch.outputs.name }}
      - run: |
          echo "name: test" > .github/workflows/new.yml
          echo "on:" >> .github/workflows/new.yml
          echo "  workflow_dispatch:" >> .github/workflows/new.yml
          echo "jobs:" >> .github/workflows/new.yml
          echo "  job1:" >> .github/workflows/new.yml
          echo "    runs-on: ubuntu-latest" >> .github/workflows/new.yml
          echo "    steps:" >> .github/workflows/new.yml
          echo "      - runs: echo oi" >> .github/workflows/new.yml
      - run: |
          git add -A
          git commit -a -m "test changing a workflow file under `.github/workflows`"
          git push -u origin ${{ steps.branch.outputs.name }}
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr create --head=${{ steps.branch.outputs.name }} \
          --title='[BOT] testing workflow changes' \
          --body='did it work?'
